server:
  port: 8800

spring:
  application:
    name: notification-service

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true