spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:8888

springdoc:
  version: '2.3.0'
  api-docs:
    version: openapi_3_1

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

management:
  tracing:
    sampling:
      probability: 1.0