spring:
  application:
    name: table-service
  config:
    import: configserver:http://localhost:8888
#  profiles:
#    active: dev
#  cloud:
#    config:
#      profile: dev

springdoc:
  version: '2.3.0'
  api-docs:
    version: openapi_3_1