# Url notification service
service:
  url:
    notification: http://localhost:8800
    product: http://localhost:9000

server:
  port: 9001
  servlet:
    context-path: /order-service

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb+srv://admin:phambaophuc@mydb.t3eg6sl.mongodb.net/fast_food_express_db
  config:
    import: 'optional:configserver:'
#  profiles:
#    active: dev
#  cloud:
#    config:
#      profile: dev

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

management:
  tracing:
    sampling:
      probability: 1.0

springdoc:
  version: '2.3.0'
  api-docs:
    version: openapi_3_1
  cache:
    disabled: true
