spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888
#  profiles:
#    active: dev
#  cloud:
#    config:
#      profile: dev

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

springdoc:
  version: '2.3.0'
  api-docs:
    version: openapi_3_1
