server:
  port: 8888

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: file://E:/Project/SpringBoot/FoodOrderXpress/config-server/src/main/resources/config-repo