server:
  port: 9002
  servlet:
    context-path: /review-service

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: review-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/review-service
  config:
    import: 'optional:configserver:'
#  profiles:
#    active: dev
#  cloud:
#    config:
#      profile: dev

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

#management:
#  tracing:
#    sampling:
#      probability: 1.0

springdoc:
  api-docs:
    version: openapi_3_1
  cache:
    disabled: true